import { PrismaClient } from "@prisma/client";
import { hashSync } from "bcrypt-ts";
const prisma = new PrismaClient();
async function main() {
  const password = hashSync("123", 10);
  const admin = await prisma.user.upsert({
    where: { email: "admin@gmail.com" },
    update: {},
    create: {
      email: "admin@gmail.com",
      name: "admin",
      role: "admin",
      password: password,
    },
  });
  const user = await prisma.user.upsert({
    where: { email: "user@gmail.com" },
    update: {},
    create: {
      email: "user@gmail.com",
      name: "user",
      password: password,
    },
  });

  const auditor = await prisma.user.upsert({
    where: { email: "auditor@gmail.com" },
    update: {},
    create: {
      email: "auditor@gmail.com",
      name: "auditor",
      role: "auditor",
      password: password,
    },
  });

  const bati_bati = await prisma.village.upsert({
    where: { slug: "bati-bati" },
    update: {},
    create: {
      name: "Desa Bati Bati",
      slug: "bati-bati",
      kecamatan: "bati bati",
      kabupaten: "Tanah Laut",
      provinsi: "Kalimantan Selatan",
      comments: {},
      budgetPeriod: {
        create: [
          {
            status: false,
            year: 2025,
            month: 12,
            name: "apdes desember 2024",
            BudgetItem: {
              create: [
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan Asli Desa",
                  name: "Hasil Usaha",
                  code: "1.1.1",
                  realization: 54000000,
                  budget: 60000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan Asli Desa",
                  name: "Hasil Aset",
                  code: "1.1.2",
                  realization: 58000000,
                  budget: 74000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan Asli Desa",
                  name: "Swadaya, Partisipasi dan Gotong Royong",
                  code: "1.1.3",
                  realization: 7000000,
                  budget: 10000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan Asli Desa",
                  name: "Lain-lain Pendapatan Asli Desa",
                  code: "1.1.4",
                  realization: 50000000,
                  budget: 39000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Transfer",
                  name: "Dana Desa",
                  code: "1.2.1",
                  realization: 830000000,
                  budget: 1000000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Transfer",
                  name: "Bagian dari Hasil Pajak dan Retribusi Daerah Kabupaten/Kota",
                  code: "1.2.2",
                  realization: 288000000,
                  budget: 390000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Transfer",
                  name: "Alokasi Dana Desa",
                  code: "1.2.3",
                  realization: 474000000,
                  budget: 500000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Transfer",
                  name: "Bantuan Keuangan Provinsi",
                  code: "1.2.4",
                  realization: 0,
                  budget: 0,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Transfer",
                  name: "Bantuan Keuangan APBD Kabupatan/Kota",
                  code: "1.2.5",
                  realization: 125000000,
                  budget: 150000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Penerimaan dari Hasil Kerjasama antar Desa",
                  code: "1.3.1",
                  realization: 77100000,
                  budget: 77100000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Penerimaan dari Hasil Kerjasama antar Desa dengan Pihak Ketiga",
                  code: "1.3.2",
                  realization: 25100000,
                  budget: 25100000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Penerimaan dari Bantuan Perusahaan yang Berlokasi di Desa",
                  code: "1.3.3",
                  realization: 50100000,
                  budget: 55100000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Hibah dan Sumbangan dari Pihak Ketiga",
                  code: "1.3.4",
                  realization: 10100000,
                  budget: 10100000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Koreksi Kesalahan Belanja Tahun-Tahun Anggaran Sebelumnya",
                  code: "1.3.5",
                  realization: 111000000,
                  budget: 111000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Lain-lain Pendapatan Desa yang Sah",
                  code: "1.3.9",
                  realization: 12000000,
                  budget: 12000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
                  name: "Penyelenggaraan Belanja Siltap, Tunjangan dan Operasional Pemerintahan",
                  code: "2.1.1",
                  realization: 550000000,
                  budget: 600000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
                  name: "Sarana dan Prasaran Pemerintah Desa",
                  code: "2.1.2",
                  realization: 95000000,
                  budget: 100000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
                  name: "Administrasi Kependudukan, Pencatatan Sipil, Statistik dan Kearsipan",
                  code: "2.1.3",
                  realization: 40000000,
                  budget: 50000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
                  name: "Tata Praja Pemerintahan, Perencanaan, Keuangan",
                  code: "2.1.4",
                  realization: 25000000,
                  budget: 30000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
                  name: "Sub Bidang Pertanahan",
                  code: "2.1.5",
                  realization: 49500000,
                  budget: 50000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Pendidikan",
                  code: "2.2.1",
                  realization: 98700000,
                  budget: 100000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Kesehatan",
                  code: "2.2.2",
                  realization: 45000000,
                  budget: 50000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Pekerjaan Umum dan Penataan Ruang",
                  code: "2.2.3",
                  realization: 8500000,
                  budget: 10000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Kawasan Pemukiman",
                  code: "2.2.4",
                  realization: 50000000,
                  budget: 50000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Kehutanan dan Lingkungan Hidup",
                  code: "2.2.5",
                  realization: 4800000,
                  budget: 5000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Perhubungan, Komunikasi dan Informatika",
                  code: "2.2.6",
                  realization: 10000000,
                  budget: 10000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Energi dan Sumber Daya Mineral",
                  code: "2.2.7",
                  realization: 4500000,
                  budget: 5000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Pariwisata",
                  code: "2.2.8",
                  realization: 3000000,
                  budget: 3000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pembinaan Kemasyarakatan",
                  name: "Ketenteraman, Ketertiban Umum, dan Perlindungan Masyarakat",
                  code: "2.3.1",
                  realization: 15000000,
                  budget: 15000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pembinaan Kemasyarakatan",
                  name: "Kebudayaan dan Keagamaan",
                  code: "2.3.2",
                  realization: 2914000,
                  budget: 3000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pembinaan Kemasyarakatan",
                  name: "Kepemudaan dan Olah Raga",
                  code: "2.3.3",
                  realization: 8500000,
                  budget: 10000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pembinaan Kemasyarakatan",
                  name: "Kelembagaan Masyarakat",
                  code: "2.3.4",
                  realization: 18000000,
                  budget: 20000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Sub Bidang Kelautan dan Perikanan",
                  code: "2.4.1",
                  realization: 5000000,
                  budget: 5000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Sub Bidang Pertanian dan Peternakan",
                  code: "2.4.2",
                  realization: 27000000,
                  budget: 30000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Sub Bidang Peningkatan Kapasitas Aparatur Desa",
                  code: "2.4.3",
                  realization: 20000000,
                  budget: 20000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Pemberdayaan Perempuan, Perlindungan Anak dan Keluarga",
                  code: "2.4.4",
                  realization: 11700000,
                  budget: 12000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Koperasi, Usaha Mikro Kecil dan Menegah (UMKM)",
                  code: "2.4.5",
                  realization: 12000000,
                  budget: 12000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Dukungan Penanaman Modal",
                  code: "2.4.6",
                  realization: 70000000,
                  budget: 72000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Perdagangan dan Perindustrian",
                  code: "2.4.7",
                  realization: 18000000,
                  budget: 20000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory:
                    "Penanggulangan Bencana, Keadaan Darurat dan Mendesak",
                  name: "Penanggulangan Bencana",
                  code: "2.5.1",
                  realization: 12000000,
                  budget: 20000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory:
                    "Penanggulangan Bencana, Keadaan Darurat dan Mendesak",
                  name: "Keadaan Darurat",
                  code: "2.5.2",
                  realization: 12000000,
                  budget: 15000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory:
                    "Penanggulangan Bencana, Keadaan Darurat dan Mendesak",
                  name: "Mendesak",
                  code: "2.5.3",
                  realization: 12000000,
                  budget: 25000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Penerimaan Pembiayaan",
                  name: "SILPA Tahun Sebelumnya",
                  code: "3.1.1",
                  realization: 10000000,
                  budget: 15000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Penerimaan Pembiayaan",
                  name: "Pencairan Dana Cadangan",
                  code: "3.1.2",
                  realization: 110000000,
                  budget: 120000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Penerimaan Pembiayaan",
                  name: "Hasil Penjualan Kekayaan Desa yang Dipisahkan",
                  code: "3.1.3",
                  realization: 20000000,
                  budget: 30000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Penerimaan Pembiayaan",
                  name: "Penerimaan Pembiayaan Lainnya",
                  code: "3.1.9",
                  realization: 25000000,
                  budget: 55000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Pengeluaran Pembiayaan",
                  name: "Pembentukan Dana Cadangan",
                  code: "3.2.1",
                  realization: 89000000,
                  budget: 95000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Pengeluaran Pembiayaan",
                  name: "Penyertaan Modal Desa",
                  code: "3.2.2",
                  realization: 10000000,
                  budget: 20000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Pengeluaran Pembiayaan",
                  name: "Pengeluaran Pembiayaan Lainnya",
                  code: "3.2.9",
                  realization: 32000000,
                  budget: 32000000,
                },
              ],
            },
          },
        ],
      },

      laporan: {},
    },
  });

  const kait_kait = await prisma.village.upsert({
    where: { slug: "kait-kait" },
    update: {},
    create: {
      name: "Desa Kait Kait",
      slug: "kait-kait",
      kecamatan: "bati bati",
      kabupaten: "Tanah Laut",
      provinsi: "Kalimantan Selatan",
      comments: {},
      budgetPeriod: {
        create: [
          {
            status: false,

            year: 2025,
            month: 1,
            name: "apdes desember 2025",
            BudgetItem: {
              create: [
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan Asli Desa",
                  name: "Hasil Usaha",
                  code: "1.1.1",
                  realization: 44000000,
                  budget: 50000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan Asli Desa",
                  name: "Hasil Aset",
                  code: "1.1.2",
                  realization: 48000000,
                  budget: 64000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan Asli Desa",
                  name: "Swadaya, Partisipasi dan Gotong Royong",
                  code: "1.1.3",
                  realization: 6000000,
                  budget: 9000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan Asli Desa",
                  name: "Lain-lain Pendapatan Asli Desa",
                  code: "1.1.4",
                  realization: 40000000,
                  budget: 49000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Transfer",
                  name: "Dana Desa",
                  code: "1.2.1",
                  realization: 830000000,
                  budget: 1000000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Transfer",
                  name: "Bagian dari Hasil Pajak dan Retribusi Daerah Kabupaten/Kota",
                  code: "1.2.2",
                  realization: 288000000,
                  budget: 390000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Transfer",
                  name: "Alokasi Dana Desa",
                  code: "1.2.3",
                  realization: 674000000,
                  budget: 800000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Transfer",
                  name: "Bantuan Keuangan Provinsi",
                  code: "1.2.4",
                  realization: 100000000,
                  budget: 120000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Transfer",
                  name: "Bantuan Keuangan APBD Kabupatan/Kota",
                  code: "1.2.5",
                  realization: 125000000,
                  budget: 150000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Penerimaan dari Hasil Kerjasama antar Desa",
                  code: "1.3.1",
                  realization: 87100000,
                  budget: 87100000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Penerimaan dari Hasil Kerjasama antar Desa dengan Pihak Ketiga",
                  code: "1.3.2",
                  realization: 29100000,
                  budget: 29100000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Penerimaan dari Bantuan Perusahaan yang Berlokasi di Desa",
                  code: "1.3.3",
                  realization: 40100000,
                  budget: 45100000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Hibah dan Sumbangan dari Pihak Ketiga",
                  code: "1.3.4",
                  realization: 12100000,
                  budget: 12100000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Koreksi Kesalahan Belanja Tahun-Tahun Anggaran Sebelumnya",
                  code: "1.3.5",
                  realization: 91000000,
                  budget: 91000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Lain-lain Pendapatan Desa yang Sah",
                  code: "1.3.9",
                  realization: 10000000,
                  budget: 12000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
                  name: "Penyelenggaraan Belanja Siltap, Tunjangan dan Operasional Pemerintahan",
                  code: "2.1.1",
                  realization: 350000000,
                  budget: 400000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
                  name: "Sarana dan Prasaran Pemerintah Desa",
                  code: "2.1.2",
                  realization: 95000000,
                  budget: 100000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
                  name: "Administrasi Kependudukan, Pencatatan Sipil, Statistik dan Kearsipan",
                  code: "2.1.3",
                  realization: 40000000,
                  budget: 50000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
                  name: "Tata Praja Pemerintahan, Perencanaan, Keuangan",
                  code: "2.1.4",
                  realization: 27000000,
                  budget: 30000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
                  name: "Sub Bidang Pertanahan",
                  code: "2.1.5",
                  realization: 49000000,
                  budget: 50000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Pendidikan",
                  code: "2.2.1",
                  realization: 99700000,
                  budget: 110000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Kesehatan",
                  code: "2.2.2",
                  realization: 35000000,
                  budget: 40000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Pekerjaan Umum dan Penataan Ruang",
                  code: "2.2.3",
                  realization: 7500000,
                  budget: 9000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Kawasan Pemukiman",
                  code: "2.2.4",
                  realization: 40000000,
                  budget: 40000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Kehutanan dan Lingkungan Hidup",
                  code: "2.2.5",
                  realization: 4800000,
                  budget: 6000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Perhubungan, Komunikasi dan Informatika",
                  code: "2.2.6",
                  realization: 8000000,
                  budget: 9000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Energi dan Sumber Daya Mineral",
                  code: "2.2.7",
                  realization: 4500000,
                  budget: 5000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Pariwisata",
                  code: "2.2.8",
                  realization: 3000000,
                  budget: 3000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pembinaan Kemasyarakatan",
                  name: "Ketenteraman, Ketertiban Umum, dan Perlindungan Masyarakat",
                  code: "2.3.1",
                  realization: 15000000,
                  budget: 15000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pembinaan Kemasyarakatan",
                  name: "Kebudayaan dan Keagamaan",
                  code: "2.3.2",
                  realization: 2914000,
                  budget: 3000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pembinaan Kemasyarakatan",
                  name: "Kepemudaan dan Olah Raga",
                  code: "2.3.3",
                  realization: 8500000,
                  budget: 10000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pembinaan Kemasyarakatan",
                  name: "Kelembagaan Masyarakat",
                  code: "2.3.4",
                  realization: 18000000,
                  budget: 20000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Sub Bidang Kelautan dan Perikanan",
                  code: "2.4.1",
                  realization: 5000000,
                  budget: 5000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Sub Bidang Pertanian dan Peternakan",
                  code: "2.4.2",
                  realization: 27000000,
                  budget: 30000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Sub Bidang Peningkatan Kapasitas Aparatur Desa",
                  code: "2.4.3",
                  realization: 20000000,
                  budget: 20000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Pemberdayaan Perempuan, Perlindungan Anak dan Keluarga",
                  code: "2.4.4",
                  realization: 11700000,
                  budget: 12000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Koperasi, Usaha Mikro Kecil dan Menegah (UMKM)",
                  code: "2.4.5",
                  realization: 12000000,
                  budget: 12000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Dukungan Penanaman Modal",
                  code: "2.4.6",
                  realization: 70000000,
                  budget: 72000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Perdagangan dan Perindustrian",
                  code: "2.4.7",
                  realization: 18000000,
                  budget: 20000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory:
                    "Penanggulangan Bencana, Keadaan Darurat dan Mendesak",
                  name: "Penanggulangan Bencana",
                  code: "2.5.1",
                  realization: 12000000,
                  budget: 20000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory:
                    "Penanggulangan Bencana, Keadaan Darurat dan Mendesak",
                  name: "Keadaan Darurat",
                  code: "2.5.2",
                  realization: 12000000,
                  budget: 15000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory:
                    "Penanggulangan Bencana, Keadaan Darurat dan Mendesak",
                  name: "Mendesak",
                  code: "2.5.3",
                  realization: 12000000,
                  budget: 25000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Penerimaan Pembiayaan",
                  name: "SILPA Tahun Sebelumnya",
                  code: "3.1.1",
                  realization: 10000000,
                  budget: 15000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Penerimaan Pembiayaan",
                  name: "Pencairan Dana Cadangan",
                  code: "3.1.2",
                  realization: 110000000,
                  budget: 120000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Penerimaan Pembiayaan",
                  name: "Hasil Penjualan Kekayaan Desa yang Dipisahkan",
                  code: "3.1.3",
                  realization: 20000000,
                  budget: 30000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Penerimaan Pembiayaan",
                  name: "Penerimaan Pembiayaan Lainnya",
                  code: "3.1.9",
                  realization: 25000000,
                  budget: 55000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Pengeluaran Pembiayaan",
                  name: "Pembentukan Dana Cadangan",
                  code: "3.2.1",
                  realization: 89000000,
                  budget: 95000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Pengeluaran Pembiayaan",
                  name: "Penyertaan Modal Desa",
                  code: "3.2.2",
                  realization: 10000000,
                  budget: 20000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Pengeluaran Pembiayaan",
                  name: "Pengeluaran Pembiayaan Lainnya",
                  code: "3.2.9",
                  realization: 32000000,
                  budget: 32000000,
                },
              ],
            },
          },
        ],
      },

      laporan: {},
    },
  });

  const ujung_harapan = await prisma.village.upsert({
    where: { slug: "ujung-harapan" },
    update: {},
    create: {
      name: "Desa Ujung Harapan",
      slug: "ujung-harapan",
      kecamatan: "Simeulue Barat",
      kabupaten: "Simeulue",
      provinsi: "Aceh",
      comments: {},
      budgetPeriod: {
        create: [
          {
            status: false,
            year: 2025,
            month: 1,
            name: "apdes januari 2025",
            BudgetItem: {
              create: [
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan Asli Desa",
                  name: "Hasil Usaha",
                  code: "1.1.1",
                  realization: 4500000,
                  budget: 60000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan Asli Desa",
                  name: "Hasil Aset",
                  code: "1.1.2",
                  realization: 6000000,
                  budget: 75000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan Asli Desa",
                  name: "Swadaya, Partisipasi dan Gotong Royong",
                  code: "1.1.3",
                  realization: 0,
                  budget: 10000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan Asli Desa",
                  name: "Lain-lain Pendapatan Asli Desa",
                  code: "1.1.4",
                  realization: 1500000,
                  budget: 40000000,
                },

                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Transfer",
                  name: "Dana Desa",
                  code: "1.2.1",
                  realization: 0,
                  budget: 1000000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Transfer",
                  name: "Bagian dari Hasil Pajak dan Retribusi Daerah Kabupaten/Kota",
                  code: "1.2.2",
                  realization: 25000000,
                  budget: 300000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Transfer",
                  name: "Alokasi Dana Desa",
                  code: "1.2.3",
                  realization: 41600000,
                  budget: 500000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Transfer",
                  name: "Bantuan Keuangan Provinsi",
                  code: "1.2.4",
                  realization: 0,
                  budget: 0,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Transfer",
                  name: "Bantuan Keuangan APBD Kabupatan/Kota",
                  code: "1.2.5",
                  realization: 0,
                  budget: 150000000,
                },

                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Penerimaan dari Hasil Kerjasama antar Desa",
                  code: "1.3.1",
                  realization: 0,
                  budget: 77100000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Penerimaan dari Hasil Kerjasama antar Desa dengan Pihak Ketiga",
                  code: "1.3.2",
                  realization: 0,
                  budget: 25100000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Penerimaan dari Bantuan Perusahaan yang Berlokasi di Desa",
                  code: "1.3.3",
                  realization: 10000000,
                  budget: 55100000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Hibah dan Sumbangan dari Pihak Ketiga",
                  code: "1.3.4",
                  realization: 0,
                  budget: 10100000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Koreksi Kesalahan Belanja Tahun-Tahun Anggaran Sebelumnya",
                  code: "1.3.5",
                  realization: 0,
                  budget: 5000000,
                },
                {
                  mainCategory: "PENDAPATAN",
                  subCategory: "Pendapatan lain-lain",
                  name: "Lain-lain Pendapatan Desa yang Sah",
                  code: "1.3.9",
                  realization: 1000000,
                  budget: 12000000,
                },

                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
                  name: "Penyelenggaraan Belanja Siltap, Tunjangan dan Operasional Pemerintahan",
                  code: "2.1.1",
                  realization: 50000000,
                  budget: 600000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
                  name: "Sarana dan Prasaran Pemerintah Desa",
                  code: "2.1.2",
                  realization: 7500000,
                  budget: 100000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
                  name: "Administrasi Kependudukan, Pencatatan Sipil, Statistik dan Kearsipan",
                  code: "2.1.3",
                  realization: 2000000,
                  budget: 50000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
                  name: "Tata Praja Pemerintahan, Perencanaan, Keuangan",
                  code: "2.1.4",
                  realization: 1500000,
                  budget: 30000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
                  name: "Sub Bidang Pertanahan",
                  code: "2.1.5",
                  realization: 0,
                  budget: 50000000,
                },

                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Pendidikan",
                  code: "2.2.1",
                  realization: 5000000,
                  budget: 100000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Kesehatan",
                  code: "2.2.2",
                  realization: 4000000,
                  budget: 50000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Pekerjaan Umum dan Penataan Ruang",
                  code: "2.2.3",
                  realization: 0,
                  budget: 100000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Kawasan Pemukiman",
                  code: "2.2.4",
                  realization: 0,
                  budget: 50000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Kehutanan dan Lingkungan Hidup",
                  code: "2.2.5",
                  realization: 0,
                  budget: 15000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Perhubungan, Komunikasi dan Informatika",
                  code: "2.2.6",
                  realization: 0,
                  budget: 25000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Energi dan Sumber Daya Mineral",
                  code: "2.2.7",
                  realization: 0,
                  budget: 5000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pelaksanaan Pembangunan Desa",
                  name: "Sub Bidang Pariwisata",
                  code: "2.2.8",
                  realization: 0,
                  budget: 20000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pembinaan Kemasyarakatan",
                  name: "Ketenteraman, Ketertiban Umum, dan Perlindungan Masyarakat",
                  code: "2.3.1",
                  realization: 2000000,
                  budget: 24000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pembinaan Kemasyarakatan",
                  name: "Kebudayaan dan Keagamaan",
                  code: "2.3.2",
                  realization: 0,
                  budget: 20000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pembinaan Kemasyarakatan",
                  name: "Kepemudaan dan Olah Raga",
                  code: "2.3.3",
                  realization: 0,
                  budget: 15000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pembinaan Kemasyarakatan",
                  name: "Kelembagaan Masyarakat",
                  code: "2.3.4",
                  realization: 0,
                  budget: 20000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Sub Bidang Kelautan dan Perikanan",
                  code: "2.4.1",
                  realization: 0,
                  budget: 25000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Sub Bidang Pertanian dan Peternakan",
                  code: "2.4.2",
                  realization: 0,
                  budget: 30000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Sub Bidang Peningkatan Kapasitas Aparatur Desa",
                  code: "2.4.3",
                  realization: 0,
                  budget: 20000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Pemberdayaan Perempuan, Perlindungan Anak dan Keluarga",
                  code: "2.4.4",
                  realization: 0,
                  budget: 12000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Koperasi, Usaha Mikro Kecil dan Menegah (UMKM)",
                  code: "2.4.5",
                  realization: 0,
                  budget: 20000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Dukungan Penanaman Modal",
                  code: "2.4.6",
                  realization: 0,
                  budget: 72000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory: "Bidang Pemberdayaan Masyarakat",
                  name: "Perdagangan dan Perindustrian",
                  code: "2.4.7",
                  realization: 0,
                  budget: 20000000,
                },

                {
                  mainCategory: "BELANJA",
                  subCategory:
                    "Penanggulangan Bencana, Keadaan Darurat dan Mendesak",
                  name: "Penanggulangan Bencana",
                  code: "2.5.1",
                  realization: 0,
                  budget: 20000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory:
                    "Penanggulangan Bencana, Keadaan Darurat dan Mendesak",
                  name: "Keadaan Darurat",
                  code: "2.5.2",
                  realization: 0,
                  budget: 15000000,
                },
                {
                  mainCategory: "BELANJA",
                  subCategory:
                    "Penanggulangan Bencana, Keadaan Darurat dan Mendesak",
                  name: "Mendesak",
                  code: "2.5.3",
                  realization: 0,
                  budget: 240000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Penerimaan Pembiayaan",
                  name: "SILPA Tahun Sebelumnya",
                  code: "3.1.1",
                  realization: 85500000,
                  budget: 85500000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Penerimaan Pembiayaan",
                  name: "Pencairan Dana Cadangan",
                  code: "3.1.2",
                  realization: 0,
                  budget: 50000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Penerimaan Pembiayaan",
                  name: "Hasil Penjualan Kekayaan Desa yang Dipisahkan",
                  code: "3.1.3",
                  realization: 0,
                  budget: 0,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Penerimaan Pembiayaan",
                  name: "Penerimaan Pembiayaan Lainnya",
                  code: "3.1.9",
                  realization: 0,
                  budget: 0,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Pengeluaran Pembiayaan",
                  name: "Pembentukan Dana Cadangan",
                  code: "3.2.1",
                  realization: 0,
                  budget: 95000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Pengeluaran Pembiayaan",
                  name: "Penyertaan Modal Desa",
                  code: "3.2.2",
                  realization: 0,
                  budget: 50000000,
                },
                {
                  mainCategory: "PEMBIAYAAN",
                  subCategory: "Pengeluaran Pembiayaan",
                  name: "Pengeluaran Pembiayaan Lainnya",
                  code: "3.2.9",
                  realization: 0,
                  budget: 0,
                },
              ],
            },
          },
        ],
      },
      laporan: {},
    },
  });

  console.log({ admin });
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
