"use server";

import { prisma } from "@/lib/prisma";
import { revalidatePath } from "next/cache";

export async function postBudgetPeriod({
  periodName,
  year,
  month,
  villageSlug,
}: {
  periodName: string;
  villageSlug: string;
  year: number;
  month: number;
}) {
  try {
    const budgetTemplateItems = [
      {
        mainCategory: "PENDAPATAN",
        subCategory: "Pendapatan Asli Desa",
        name: "Hasil Usaha",
        code: "1.1.1",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PENDAPATAN",
        subCategory: "Pendapatan Asli Desa",
        name: "Hasil Aset",
        code: "1.1.2",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PENDAPATAN",
        subCategory: "Pendapatan Asli Desa",
        name: "Swadaya, Partisipasi dan Gotong Royong",
        code: "1.1.3",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PENDAPATAN",
        subCategory: "Pendapatan Asli Desa",
        name: "Lain-lain Pendapatan Asli Desa",
        code: "1.1.4",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PENDAPATAN",
        subCategory: "Transfer",
        name: "Dana Desa",
        code: "1.2.1",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PENDAPATAN",
        subCategory: "Transfer",
        name: "Bagian dari Hasil Pajak dan Retribusi Daerah Kabupaten/Kota",
        code: "1.2.2",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PENDAPATAN",
        subCategory: "Transfer",
        name: "Alokasi Dana Desa",
        code: "1.2.3",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PENDAPATAN",
        subCategory: "Transfer",
        name: "Bantuan Keuangan Provinsi",
        code: "1.2.4",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PENDAPATAN",
        subCategory: "Transfer",
        name: "Bantuan Keuangan APBD Kabupatan/Kota",
        code: "1.2.5",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PENDAPATAN",
        subCategory: "Pendapatan lain-lain",
        name: "Penerimaan dari Hasil Kerjasama antar Desa",
        code: "1.3.1",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PENDAPATAN",
        subCategory: "Pendapatan lain-lain",
        name: "Penerimaan dari Hasil Kerjasama antar Desa dengan Pihak Ketiga",
        code: "1.3.2",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PENDAPATAN",
        subCategory: "Pendapatan lain-lain",
        name: "Penerimaan dari Bantuan Perusahaan yang Berlokasi di Desa",
        code: "1.3.3",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PENDAPATAN",
        subCategory: "Pendapatan lain-lain",
        name: "Hibah dan Sumbangan dari Pihak Ketiga",
        code: "1.3.4",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PENDAPATAN",
        subCategory: "Pendapatan lain-lain",
        name: "Koreksi Kesalahan Belanja Tahun-Tahun Anggaran Sebelumnya",
        code: "1.3.5",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PENDAPATAN",
        subCategory: "Pendapatan lain-lain",
        name: "Lain-lain Pendapatan Desa yang Sah",
        code: "1.3.9",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
        name: "Penyelenggaraan Belanja Siltap, Tunjangan dan Operasional Pemerintahan",
        code: "2.1.1",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
        name: "Sarana dan Prasaran Pemerintah Desa",
        code: "2.1.2",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
        name: "Administrasi Kependudukan, Pencatatan Sipil, Statistik dan Kearsipan",
        code: "2.1.3",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
        name: "Tata Praja Pemerintahan, Perencanaan, Keuangan",
        code: "2.1.4",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Penyelenggaraan Pemerintahan Desa",
        name: "Sub Bidang Pertanahan",
        code: "2.1.5",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pelaksanaan Pembangunan Desa",
        name: "Sub Bidang Pendidikan",
        code: "2.2.1",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pelaksanaan Pembangunan Desa",
        name: "Sub Bidang Kesehatan",
        code: "2.2.2",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pelaksanaan Pembangunan Desa",
        name: "Sub Bidang Pekerjaan Umum dan Penataan Ruang",
        code: "2.2.3",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pelaksanaan Pembangunan Desa",
        name: "Sub Bidang Kawasan Pemukiman",
        code: "2.2.4",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pelaksanaan Pembangunan Desa",
        name: "Sub Bidang Kehutanan dan Lingkungan Hidup",
        code: "2.2.5",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pelaksanaan Pembangunan Desa",
        name: "Sub Bidang Perhubungan, Komunikasi dan Informatika",
        code: "2.2.6",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pelaksanaan Pembangunan Desa",
        name: "Sub Bidang Energi dan Sumber Daya Mineral",
        code: "2.2.7",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pelaksanaan Pembangunan Desa",
        name: "Sub Bidang Pariwisata",
        code: "2.2.8",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pembinaan Kemasyarakatan",
        name: "Ketenteraman, Ketertiban Umum, dan Perlindungan Masyarakat",
        code: "2.3.1",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pembinaan Kemasyarakatan",
        name: "Kebudayaan dan Keagamaan",
        code: "2.3.2",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pembinaan Kemasyarakatan",
        name: "Kepemudaan dan Olah Raga",
        code: "2.3.3",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pembinaan Kemasyarakatan",
        name: "Kelembagaan Masyarakat",
        code: "2.3.4",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pemberdayaan Masyarakat",
        name: "Sub Bidang Kelautan dan Perikanan",
        code: "2.4.1",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pemberdayaan Masyarakat",
        name: "Sub Bidang Pertanian dan Peternakan",
        code: "2.4.2",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pemberdayaan Masyarakat",
        name: "Sub Bidang Peningkatan Kapasitas Aparatur Desa",
        code: "2.4.3",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pemberdayaan Masyarakat",
        name: "Pemberdayaan Perempuan, Perlindungan Anak dan Keluarga",
        code: "2.4.4",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pemberdayaan Masyarakat",
        name: "Koperasi, Usaha Mikro Kecil dan Menegah (UMKM)",
        code: "2.4.5",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pemberdayaan Masyarakat",
        name: "Dukungan Penanaman Modal",
        code: "2.4.6",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Bidang Pemberdayaan Masyarakat",
        name: "Perdagangan dan Perindustrian",
        code: "2.4.7",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Penanggulangan Bencana, Keadaan Darurat dan Mendesak",
        name: "Penanggulangan Bencana",
        code: "2.5.1",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Penanggulangan Bencana, Keadaan Darurat dan Mendesak",
        name: "Keadaan Darurat",
        code: "2.5.2",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "BELANJA",
        subCategory: "Penanggulangan Bencana, Keadaan Darurat dan Mendesak",
        name: "Mendesak",
        code: "2.5.3",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PEMBIAYAAN",
        subCategory: "Penerimaan Pembiayaan",
        name: "SILPA Tahun Sebelumnya",
        code: "3.1.1",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PEMBIAYAAN",
        subCategory: "Penerimaan Pembiayaan",
        name: "Pencairan Dana Cadangan",
        code: "3.1.2",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PEMBIAYAAN",
        subCategory: "Penerimaan Pembiayaan",
        name: "Hasil Penjualan Kekayaan Desa yang Dipisahkan",
        code: "3.1.3",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PEMBIAYAAN",
        subCategory: "Penerimaan Pembiayaan",
        name: "Penerimaan Pembiayaan Lainnya",
        code: "3.1.9",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PEMBIAYAAN",
        subCategory: "Pengeluaran Pembiayaan",
        name: "Pembentukan Dana Cadangan",
        code: "3.2.1",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PEMBIAYAAN",
        subCategory: "Pengeluaran Pembiayaan",
        name: "Penyertaan Modal Desa",
        code: "3.2.2",
        realization: 0,
        budget: 0,
      },
      {
        mainCategory: "PEMBIAYAAN",
        subCategory: "Pengeluaran Pembiayaan",
        name: "Pengeluaran Pembiayaan Lainnya",
        code: "3.2.9",
        realization: 0,
        budget: 0,
      },
    ];
    const budgetPeriod = await prisma.budgetPeriod.create({
      data: {
        name: periodName,
        year,
        month,
        BudgetItem: {
          create: budgetTemplateItems.map((item) => ({
            mainCategory: item.mainCategory || "",
            subCategory: item.subCategory || "",
            name: item.name || "",
            code: item.code || "",  
            realization: item.realization || 0,
            budget: item.budget || 0,
          })),
        },
        village: {
          connect: {
            slug: villageSlug,
          },
        },
      },
    });

    console.log(
      `✅ Created budget items for ${villageSlug} - ${periodName} ${year}-${month}`
    );
    revalidatePath(`/village/${villageSlug}`);

    return { success: true };
  } catch (err) {
    console.error(err);
    return { success: false, message: "Gagal menambahkan komentar." };
  }
}
